### ISSUE TITLE
Error critíco

### ISSUE THREAD

**Issue by luccaeZ** [JLCareglio/Steam-Profit-Maker#1]
Intente usar vpn y sigue igual
![image](https://user-images.githubusercontent.com/124004387/215617285-24f7d54f-9c06-4418-8846-c7d6327ea02f.png)

**Comment by JLCareglio** [comment]
👋 Buenas tardes, el juego con APPID 486120 no genera ningún error y si puede ser escaneado correctamente:
![486120](https://user-images.githubusercontent.com/23004689/215844206-b7062154-dd19-4b12-96eb-e36e32a3e7c6.png)

🟡 Para usar SPM actualmente se requieren entre otras cosas, unos conocimientos avanzados en Python y Poetry.

🟢 Quiero que todos puedan usar SPM por lo que en los siguientes días subiré unos archivos ejecutables en la sección de [Releases](https://github.com/JLCareglio/Steam-Profit-Maker/releases) para ofrecer compatibilidad con Windows y Linux. 😲 Usando estos archivos (disponibles en un futuro) cualquiera podrá abrir y usar SPM y sin complicaciones 😁👍.

🔵 Ya mismo actualizaré el readme para incluir los requisitos y librerías necesarias por si algún dev desea trabajar con el código fuente, adelanto que si no se usa Poetry también se pueden instalar las librerías manualmente con:
`pip3 install beautifulsoup4 bs4 certifi charset-normalizer colorama idna python-dotenv requests soupsieve urllib3`
⚠️ Otra aclaración importante es que por ahora el proyecto solamente funciona con Python 3.9 o superior, en Terminales UNIX y teóricamente en PowerShell de Windows (no probado en PowerShell).

🔴 CMD de Windows dará errores.

😄 Gracias por mostrar interés en mi trabajo, recuerda que puedes agregarlo a favoritos ⭐ para estar atento cuando salga la primera versión. Salu2 👋

**Comment by luccaeZ** [comment]
y cual es el programa que usted usa para abrir SPM? yo solo intente con cmd y va bien algún que otro error con los ID's de los juegos pero bien

**Comment by JLCareglio** [comment]
> 

🤔 En mi caso eso depende de donde esté trabajando, puedo contarte si quieres con que abro SPM:
- Si estoy en [Pop!_OS](https://pop.system76.com/) (u otra distro de linux) abro SPM usando la terminal nativa pero con ZSH  instalado y [OhMyZsh](https://ohmyz.sh/) + plugins.
- Si estoy en Windows, utilizo [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) para abrir comúnmente Ubuntu en la [terminal oficial de Windows](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) y también le instalo ZSH + [OhMyZsh](https://ohmyz.sh/) + plugins.
- Si estoy en un equipo de bajos recursos con Windows, suelo instalar y trabajar con [GitBash](https://git-scm.com/downloads)

✅ En Windows me gusta recomendar instalar y usar [GitBash ](https://git-scm.com/downloads) o PowerShell, ambos se pueden abrir desde la [Terminal Oficial de Windows](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) y SPM tendría que funcionar con cualquiera de los 2.

También recomiendo tener una conexión a internet estable y cambiar de VPN o Proxy luego de muchos usos, ya que Steam termina bloqueando temporalmente las conexiones luego de varias consultas a su API.
